# Generated by Django 5.0.7 on 2025-10-23 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="pendiente", max_length=30)),
                (
                    "preference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="ordenes.orden",
                    ),
                ),
            ],
        ),
    ]
