# Generated by Django 5.0.7 on 2025-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recibir_bienvenida",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Bienvenida"
                    ),
                ),
                (
                    "recibir_confirmaciones",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Confirmaciones"
                    ),
                ),
                (
                    "recibir_orden_updates",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Actualizaciones de Órdenes"
                    ),
                ),
                (
                    "recibir_promociones",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Promociones"
                    ),
                ),
                (
                    "recibir_newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Recibir Newsletter"
                    ),
                ),
                (
                    "recibir_ofertas",
                    models.BooleanField(
                        default=True, verbose_name="Recibir Ofertas Especiales"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de Notificación",
                "verbose_name_plural": "Configuraciones de Notificación",
            },
        ),
        migrations.CreateModel(
            name="NotificacionCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bienvenida", "Bienvenida"),
                            ("confirmacion_registro", "Confirmación de Registro"),
                            ("confirmacion_email", "Confirmación de Email"),
                            ("reseteo_password", "Reseteo de Contraseña"),
                            ("orden_confirmada", "Orden Confirmada"),
                            ("orden_enviada", "Orden Enviada"),
                            ("orden_entregada", "Orden Entregada"),
                            ("orden_cancelada", "Orden Cancelada"),
                            ("pago_exitoso", "Pago Exitoso"),
                            ("pago_fallido", "Pago Fallido"),
                            ("producto_disponible", "Producto Disponible"),
                            ("oferta_especial", "Oferta Especial"),
                            ("newsletter", "Newsletter"),
                            ("promocion", "Promoción"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                (
                    "email_destinatario",
                    models.EmailField(
                        max_length=254, verbose_name="Email Destinatario"
                    ),
                ),
                ("asunto", models.CharField(max_length=200, verbose_name="Asunto")),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviada", "Enviada"),
                            ("fallida", "Fallida"),
                            ("programada", "Programada"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Programada"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "orden_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de Orden"
                    ),
                ),
                (
                    "producto_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de Producto"
                    ),
                ),
                (
                    "datos_adicionales",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos Adicionales"
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de Error"
                    ),
                ),
                (
                    "intentos_envio",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos de Envío"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de Correo",
                "verbose_name_plural": "Notificaciones de Correo",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="TemplateCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("bienvenida", "Bienvenida"),
                            ("confirmacion_registro", "Confirmación de Registro"),
                            ("confirmacion_email", "Confirmación de Email"),
                            ("reseteo_password", "Reseteo de Contraseña"),
                            ("orden_confirmada", "Orden Confirmada"),
                            ("orden_enviada", "Orden Enviada"),
                            ("orden_entregada", "Orden Entregada"),
                            ("orden_cancelada", "Orden Cancelada"),
                            ("pago_exitoso", "Pago Exitoso"),
                            ("pago_fallido", "Pago Fallido"),
                            ("producto_disponible", "Producto Disponible"),
                            ("oferta_especial", "Oferta Especial"),
                            ("newsletter", "Newsletter"),
                            ("promocion", "Promoción"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Tipo de Notificación",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Template"
                    ),
                ),
                (
                    "asunto",
                    models.CharField(max_length=200, verbose_name="Asunto del Email"),
                ),
                ("contenido_html", models.TextField(verbose_name="Contenido HTML")),
                (
                    "contenido_texto",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido en Texto Plano"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template de Correo",
                "verbose_name_plural": "Templates de Correo",
                "ordering": ["tipo"],
            },
        ),
    ]
