# Generated by Django 5.0.7 on 2025-10-23 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notificaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracionnotificacion",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_notificaciones",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="notificacioncorreo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificaciones_correo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacioncorreo",
            index=models.Index(
                fields=["usuario", "tipo"], name="notificacio_usuario_2b0186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacioncorreo",
            index=models.Index(
                fields=["estado", "fecha_programada"],
                name="notificacio_estado_50ce51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacioncorreo",
            index=models.Index(
                fields=["fecha_envio"], name="notificacio_fecha_e_710638_idx"
            ),
        ),
    ]
