# Generated by Django 5.0.7 on 2025-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "email_invitado",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "nombre_invitado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telefono_invitado",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("direccion_invitado", models.TextField(blank=True, null=True)),
                (
                    "metodo_entrega",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery a Domicilio"),
                            ("retiro", "Retiro en Tienda"),
                        ],
                        default="delivery",
                        max_length=20,
                        verbose_name="Método de Entrega",
                    ),
                ),
                (
                    "costo_envio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("procesando", "Procesando"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=30,
                        verbose_name="Estado de la Orden",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="OrdenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("producto_id", models.IntegerField()),
                ("nombre_producto", models.CharField(max_length=200)),
                (
                    "precio_producto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
