"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import Config, RepositoryEnv
import os

# Configurar PyMySQL como reemplazo de MySQLdb
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar si estamos en producción o desarrollo
# En producción, buscará .env en el directorio del proyecto
# En desarrollo, usará .env.production para testing
ENV_FILE = BASE_DIR / '.env'
if not ENV_FILE.exists():
    ENV_FILE = BASE_DIR / '.env.production'

config = Config(RepositoryEnv(str(ENV_FILE))) if ENV_FILE.exists() else Config()

# Build paths inside th# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-gm0259k-q8e4^$*rj=2*!gf*h4#e&4-yi7p$)*ki14lxlr_sv!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Leer ALLOWED_HOSTS del .env (separados por comas)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# ================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO - RESEND
# ================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM', default='onboarding@resend.dev')
EMAIL_FROM = config('EMAIL_FROM', default='onboarding@resend.dev')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'usuarios',
    'rest_framework',
    'productos',
    'carrito',
    'ordenes',
    'pagos',
    'envios',
    'ofertas',
    'deseos',
    'analitica',
    'notificaciones',  # Nueva app para notificaciones por correo
    'corsheaders',
    'drf_spectacular',
    'categorias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para archivos estáticos
    'corsheaders.middleware.CorsMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # URL de tu frontend en desarrollo (ajústalo según sea necesario)
    "https://tu_dominio.com", 
    "http://localhost:5173",
    "http://localhost:5174",
    "https://lifesexshop.cl",
    "http://lifesexshop.cl",
    "https://www.lifesexshop.cl",  # Con www
    "http://www.lifesexshop.cl",   # Con www
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'Authorization',
    'accept',
    'X-Requested-With',
    'X-CSRFToken',
    'csrftoken',
]
CORS_ALLOW_CREDENTIALS = True

# Configuración CSRF para producción
CSRF_TRUSTED_ORIGINS = [
    "https://lifesexshop.cl",
    "http://lifesexshop.cl",
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'staticfiles' / 'frontend',  # Para React en producción
            BASE_DIR / 'static' / 'frontend',        # Para React en desarrollo
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuración de base de datos: MySQL en producción, SQLite en desarrollo
if config('DB_NAME', default=None):
    # Producción - MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Desarrollo - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Legacy: Configuración para producción con MySQL (descomentar en producción)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='3306'),
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'usuarios.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "home/lifesexs/public_html/statics"

# Para desarrollo - directorio de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CONFIGURACIÓN CORREGIDA DE REST FRAMEWORK
# CONFIGURACIÓN CORREGIDA DE REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
   'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.AllowAny', 
],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Archivos de medios (para imágenes de productos, documentos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Life Sex Shop",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Life Sex Shop Admin",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": None,

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Bienvenido",

    # Copyright on the footer
    "copyright": "weblogica.cl",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["auth.Productos", "auth.Group"],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": ["envios.Envio"],  # Ocultar el modelo Envio para evitar redundancia

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["productos", "ordenes", "ofertas", "categorias", "carrito", "usuarios", "analitica", "deseos", "pagos", "auth"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "productos": [{
            "name": " Reporte de Inventario", 
            "url": "/admin/productos/producto/?stock__lt=10", 
            "icon": "fas fa-chart-line",
            "permissions": ["productos.view_producto"]
        }, {
            "name": " Productos Agotados", 
            "url": "/admin/productos/producto/?stock__exact=0", 
            "icon": "fas fa-exclamation-triangle",
            "permissions": ["productos.view_producto"]
        }],
        "ofertas": [{
            "name": " Ofertas Activas", 
            "url": "/admin/ofertas/oferta/?activo__exact=1", 
            "icon": "fas fa-fire",
            "permissions": ["ofertas.view_oferta"]
        }],
        "ordenes": [{
            "name": " Órdenes Pendientes", 
            "url": "/admin/ordenes/orden/?estado__exact=pendiente", 
            "icon": "fas fa-clock",
            "permissions": ["ordenes.view_orden"]
        }, {
            "name": " Órdenes Enviadas", 
            "url": "/admin/ordenes/orden/?estado__exact=enviado", 
            "icon": "fas fa-truck",
            "permissions": ["ordenes.view_orden"]
        }, {
            "name": " Reporte de Ventas", 
            "url": "/admin/ordenes/orden/?fecha__gte=2024-01-01", 
            "icon": "fas fa-dollar-sign",
            "permissions": ["ordenes.view_orden"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "productos": "fas fa-boxes",
        "productos.Producto": "fas fa-box",
        "ofertas": "fas fa-tags",
        "ofertas.Oferta": "fas fa-tag",
        "categorias": "fas fa-list",
        "categorias.Categoria": "fas fa-folder",
        "carrito": "fas fa-shopping-cart",
        "carrito.Carrito": "fas fa-cart-plus",
        "ordenes": "fas fa-file-invoice-dollar",
        "ordenes.Orden": "fas fa-receipt",
        "ordenes.OrdenProducto": "fas fa-list-alt",
        "usuarios": "fas fa-users",
        "usuarios.Usuario": "fas fa-user-circle",
        "analitica": "fas fa-chart-bar",
        "analitica.Analitica": "fas fa-analytics",
        "envios": "fas fa-truck",
        "envios.Envio": "fas fa-shipping-fast",
        "deseos": "fas fa-heart",
        "pagos": "fas fa-credit-card",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "single",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs",
        "productos.producto": "single"  # Productos en formato simple
    },
    # Add a language dropdown into the admin
    "language_chooser": False,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),      
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      
    'ROTATE_REFRESH_TOKENS': True,                    
    'BLACKLIST_AFTER_ROTATION': True,                
    'UPDATE_LAST_LOGIN': True,                        
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # True en producción con HTTPS  
SESSION_COOKIE_HTTPONLY = False  # CAMBIO CRÍTICO: Permitir acceso desde JavaScript
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 1209600  # 2 semanas

# URL del sitio para webhooks
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# ================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO - SENDGRID (SIN DNS REQUERIDO)
# ================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # Siempre es 'apikey' para SendGrid
EMAIL_HOST_PASSWORD = config('SENDGRID_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM', default='contacto@lifesexshop.cl')
EMAIL_FROM = config('EMAIL_FROM', default='contacto@lifesexshop.cl')

# ================================================================
# MERCADOPAGO CONFIGURACIÓN
# ================================================================
MERCADOPAGO_PUBLIC_KEY = config('MERCADOPAGO_PUBLIC_KEY', default='')
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='')
MERCADOPAGO_WEBHOOK_URL = config('MERCADOPAGO_WEBHOOK_URL', default='')
MERCADOPAGO_SUCCESS_URL = config('MERCADOPAGO_SUCCESS_URL', default='')
MERCADOPAGO_FAILURE_URL = config('MERCADOPAGO_FAILURE_URL', default='')
MERCADOPAGO_PENDING_URL = config('MERCADOPAGO_PENDING_URL', default='')