# Este es Copílot comentando
"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import Config, RepositoryEnv
import os

# Configurar PyMySQL como reemplazo de MySQLdb
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar si estamos en producción o desarrollo
# En producción, buscará .env en el directorio del proyecto
# En desarrollo, usará .env.production para testing
ENV_FILE = BASE_DIR / '.env'
if not ENV_FILE.exists():
    ENV_FILE = BASE_DIR / '.env.production'

config = Config(RepositoryEnv(str(ENV_FILE))) if ENV_FILE.exists() else Config(RepositoryEnv(''))

# Build paths inside th# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-gm0259k-q8e4^$*rj=2*!gf*h4#e&4-yi7p$)*ki14lxlr_sv!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Leer ALLOWED_HOSTS del .env (separados por comas)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# ================================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO - RESEND
# ================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM', default='onboarding@resend.dev')
EMAIL_FROM = config('EMAIL_FROM', default='onboarding@resend.dev')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'usuarios',
    'rest_framework',
    'productos',
    'carrito',
    'ordenes',
    'pagos',
    'envios',
    'ofertas',
    'deseos',
    'analitica',
    'notificaciones',  
    'corsheaders',
    'drf_spectacular',
    'categorias',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", 
    "https://tu_dominio.com", 
    "http://localhost:5173",
    "http://localhost:5174",
  
]

CORS_ALLOW_HEADERS = [
    'content-type',
    'Authorization',
    'accept',
    'X-Requested-With',
    'X-CSRFToken',
    'csrftoken',
]
CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://tu_dominio.com"
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'staticfiles' / 'frontend',
            BASE_DIR / 'static' / 'frontend',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'





DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'usuarios.Usuario'


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = '/static/'
STATIC_ROOT = "statics"


STATICFILES_DIRS = [
    BASE_DIR / 'static',
]



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
   'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.AllowAny', 
],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

JAZZMIN_SETTINGS = {
    
    "site_title": "PerfumeriApp",

    
    "site_brand": "PerfumeriApp Admin",

    
    "site_logo": None,

    
    "login_logo": None,

    
    "login_logo_dark": None,

    
    "site_logo_classes": "img-circle",

    
    "site_icon": None,

    
    "welcome_sign": "Bienvenido",


    "copyright": "weblogica.cl",

    "search_model": ["auth.Productos", "auth.Group"],

    "user_avatar": None,

    "topmenu_links": [


        {"name": "Inicio",  "url": "admin:index", "permissions": ["auth.view_user"]},

        {"model": "auth.User"},


        {"app": "books"},
    ],


    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],


    "show_sidebar": True,


    "navigation_expanded": True,


    "hide_apps": [],


    "hide_models": ["envios.Envio"],  

    "order_with_respect_to": ["productos", "ordenes", "ofertas", "categorias", "carrito", "usuarios", "analitica", "deseos", "pagos", "auth"],


    "custom_links": {
        "productos": [{
            "name": " Reporte de Inventario", 
            "url": "/admin/productos/producto/?stock__lt=10", 
            "icon": "fas fa-chart-line",
            "permissions": ["productos.view_producto"]
        }, {
            "name": " Productos Agotados", 
            "url": "/admin/productos/producto/?stock__exact=0", 
            "icon": "fas fa-exclamation-triangle",
            "permissions": ["productos.view_producto"]
        }],
        "ofertas": [{
            "name": " Ofertas Activas", 
            "url": "/admin/ofertas/oferta/?activo__exact=1", 
            "icon": "fas fa-fire",
            "permissions": ["ofertas.view_oferta"]
        }],
        "ordenes": [{
            "name": " Órdenes Pendientes", 
            "url": "/admin/ordenes/orden/?estado__exact=pendiente", 
            "icon": "fas fa-clock",
            "permissions": ["ordenes.view_orden"]
        }, {
            "name": " Órdenes Enviadas", 
            "url": "/admin/ordenes/orden/?estado__exact=enviado", 
            "icon": "fas fa-truck",
            "permissions": ["ordenes.view_orden"]
        }, {
            "name": " Reporte de Ventas", 
            "url": "/admin/ordenes/orden/?fecha__gte=2024-01-01", 
            "icon": "fas fa-dollar-sign",
            "permissions": ["ordenes.view_orden"]
        }]
    },


    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "productos": "fas fa-boxes",
        "productos.Producto": "fas fa-box",
        "ofertas": "fas fa-tags",
        "ofertas.Oferta": "fas fa-tag",
        "categorias": "fas fa-list",
        "categorias.Categoria": "fas fa-folder",
        "carrito": "fas fa-shopping-cart",
        "carrito.Carrito": "fas fa-cart-plus",
        "ordenes": "fas fa-file-invoice-dollar",
        "ordenes.Orden": "fas fa-receipt",
        "ordenes.OrdenProducto": "fas fa-list-alt",
        "usuarios": "fas fa-users",
        "usuarios.Usuario": "fas fa-user-circle",
        "analitica": "fas fa-chart-bar",
        "analitica.Analitica": "fas fa-analytics",
        "envios": "fas fa-truck",
        "envios.Envio": "fas fa-shipping-fast",
        "deseos": "fas fa-heart",
        "pagos": "fas fa-credit-card",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",


    "related_modal_active": False,


    "custom_css": None,
    "custom_js": None,

    "use_google_fonts_cdn": True,

    "show_ui_builder": False,


    "changeform_format": "single",

    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs",
        "productos.producto": "single"  
    },

    "language_chooser": False,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),      
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      
    'ROTATE_REFRESH_TOKENS': True,                    
    'BLACKLIST_AFTER_ROTATION': True,                
    'UPDATE_LAST_LOGIN': True,                        
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  
SESSION_COOKIE_HTTPONLY = False  
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 1209600  


SITE_URL = config('SITE_URL', default='http://localhost:8000')


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey' 
EMAIL_HOST_PASSWORD = config('SENDGRID_API_KEY', default='')
DEFAULT_FROM_EMAIL = config('EMAIL_FROM', default='contacto@lifesexshop.cl')
EMAIL_FROM = config('EMAIL_FROM', default='contacto@lifesexshop.cl')


MERCADOPAGO_PUBLIC_KEY = config('MERCADOPAGO_PUBLIC_KEY', default='')
MERCADOPAGO_ACCESS_TOKEN = config('MERCADOPAGO_ACCESS_TOKEN', default='')
MERCADOPAGO_WEBHOOK_URL = config('MERCADOPAGO_WEBHOOK_URL', default='')
MERCADOPAGO_SUCCESS_URL = config('MERCADOPAGO_SUCCESS_URL', default='')
MERCADOPAGO_FAILURE_URL = config('MERCADOPAGO_FAILURE_URL', default='')
MERCADOPAGO_PENDING_URL = config('MERCADOPAGO_PENDING_URL', default='')