# Generated by Django 4.2.7 on 2025-09-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='porcentaje_descuento',
            field=models.PositiveIntegerField(help_text='Porcentaje de descuento (ej: 25 para 25%)'),
        ),
    ]
