# Generated by Django 4.2.7 on 2025-09-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analitica',
            options={'ordering': ['-fecha']},
        ),
    ]
