# Generated by Django 4.2.7 on 2025-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0003_alter_orden_options_alter_orden_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("pagado", "Pagado"),
                    ("procesando", "Procesando"),
                    ("enviado", "Enviado"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=30,
                verbose_name="Estado de la Orden",
            ),
        ),
    ]
