# Generated by Django 4.2.7 on 2025-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0004_alter_orden_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="costo_envio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="orden",
            name="metodo_entrega",
            field=models.CharField(
                choices=[
                    ("delivery", "Delivery a Domicilio"),
                    ("retiro", "Retiro en Tienda"),
                ],
                default="delivery",
                max_length=20,
                verbose_name="Método de Entrega",
            ),
        ),
    ]
