# Generated by Django 5.0.7 on 2025-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                ("tipo", models.CharField(default="retiro", max_length=30)),
                ("estado", models.CharField(default="pendiente", max_length=30)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
