# Generated by Django 5.0.7 on 2025-10-23 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("envios", "0001_initial"),
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="envio",
            name="orden",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envios",
                to="ordenes.orden",
            ),
        ),
    ]
