# Generated by Django 5.0.7 on 2025-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analitica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=100)),
                ("valor", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
