# Generated by Django 5.0.7 on 2025-10-23 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carrito", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="carrito",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carritos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="carrito",
            constraint=models.UniqueConstraint(
                condition=models.Q(("usuario__isnull", False)),
                fields=("usuario", "producto"),
                name="unique_user_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="carrito",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key", "producto"),
                name="unique_session_product",
            ),
        ),
    ]
