# Generated by Django 4.2.7 on 2025-09-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_ciudad_usuario_codigo_postal_usuario_comuna_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username']},
        ),
    ]
